input {
  syslog {
    port => 1514
    timezone => "${SYSLOG_TIMEZONE:UTC}"
  }

  syslog {
    port => 1515
    timezone => "${SYSLOG_TIMEZONE:UTC}"
    add_field => { "syslog_router" => "true" }
  }
}
